name: my_documentation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  tutorial_coach_mark: ^1.2.9
  clay_containers: ^0.3.2
  sqlite3_flutter_libs: ^0.5.15
  drift: ^2.10.0
  drift_dev: ^2.10.0
  expandable_bottom_sheet: ^1.1.1+1
  path_provider: ^2.1.0
  drift_db_viewer: ^2.0.0
  http: ^1.1.0
  dio: ^5.3.2
  table_calendar: ^3.0.9
  flame: ^1.8.2
  video_player: ^2.7.2
  lottie: ^2.6.0
  faker: ^2.1.0
  shimmer: ^3.0.0
  fl_chart: ^0.64.0

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/video/
    - assets/lotties/
